// <auto-generated />
using System;
using AnagramSolver.EF.CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnagramSolver.EF.CodeFirst.Migrations
{
    [DbContext(typeof(AnagramSolverCodeFirstContext))]
    partial class AnagramSolverCodeFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AnagramSolver.Contracts.Models.CachedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CachedWords");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.SearchInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Anagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SearchTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SearchedWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SearchInformations");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OrderedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.WordCachedWordAdditional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CachedWordId")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CachedWordId");

                    b.HasIndex("WordId");

                    b.ToTable("WordCachedWordAdditionals");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.WordCachedWordAdditional", b =>
                {
                    b.HasOne("AnagramSolver.Contracts.Models.CachedWord", "CachedWord")
                        .WithMany("WordCachedWordAdditionals")
                        .HasForeignKey("CachedWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnagramSolver.Contracts.Models.Word", "Word")
                        .WithMany("WordCachedWordAdditionals")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CachedWord");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.CachedWord", b =>
                {
                    b.Navigation("WordCachedWordAdditionals");
                });

            modelBuilder.Entity("AnagramSolver.Contracts.Models.Word", b =>
                {
                    b.Navigation("WordCachedWordAdditionals");
                });
#pragma warning restore 612, 618
        }
    }
}
